#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

START=90
INTERFACE=br-lan
PORT=1337

# check if configuration exists
[ -e "/etc/redsocks.conf" ] || exit 0

# List of Bangladeshi IP address ranges to exclude from redsocks
BD_IPS="103.159.128.0/24
103.122.143.0/24 \
103.177.246.0/24 \
103.106.238.0/24 \
180.211.201.0/24 \
103.20.141.0/24 \
115.108.49.0/24 \
114.130.226.0/24 \
180.211.173.0/24 \
103.239.255.0/25 \
103.106.237.0/24 \
202.22.192.0/20 \
103.238.217.0/24 \
103.41.213.0/24 \
23.192.0.0/11 \
154.85.74.0/24 \
103.120.202.0/24 \
71.18.0.0/16 \
199.232.0.0/16 \
96.16.0.0/15 \
184.84.0.0/14 \
104.64.0.0/10 \
103.12.74.0/24 \
103.136.220.0/24 \
23.32.0.0/11 \
23.64.0.0/14 \
151.101.0.0/16"
iptable_start() {
    /bin/echo -n "running redsocks iptables ..."

    # Run iptable commands
    iptables -t nat -N REDSOCKS

    # Exclude private networks and Bangladeshi IP addresses
    iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
    iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
    iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
    iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
    iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
    iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
    iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
    iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN

    for IP in $BD_IPS; do
        iptables -t nat -A REDSOCKS -d $IP -j RETURN
    done

    iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports ${PORT}

    iptables -t nat -A PREROUTING -i ${INTERFACE} -p tcp -j REDSOCKS

    iptables -A INPUT -i br-lan -p tcp --dport ${PORT} -j ACCEPT

    /bin/echo " done"
}

iptable_stop() {
    /bin/echo -n "cleaning redsocks iptables ..."

    # Run iptable commands
    iptables -t nat -F REDSOCKS
    iptables -t nat -F PREROUTING
    iptables -t nat -F POSTROUTING
    iptables -F INPUT
    iptables -F FORWARD
    iptables -t nat -X REDSOCKS

    /bin/echo " done"
}

start() {
    if [ -e "/var/run/redsocks.pid" ]; then
        echo "redsocks is already running"
        exit 0
    fi

    /bin/echo -n "running redsocks ..."

    # startup the safety-wrapper for the daemon
    /usr/sbin/redsocks -p /var/run/redsocks.pid

    /bin/echo " done"
    iptable_start
}

stop() {
    if [ ! -e "/var/run/redsocks.pid" ]; then
        echo "redsocks is not running"
        exit 0
    fi

    /bin/echo -n "stopping redsocks ..."

    # kill the process
    /bin/kill $(cat /var/run/redsocks.pid)
    rm /var/run/redsocks.pid

    echo " done"
    iptable_stop

    /bin/echo -n "restarting firewall ..."
    /etc/init.d/firewall restart &> /dev/null
    /bin/echo " done"
}
